// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_analytics from "./routes/admin/analytics.tsx";
import * as $admin_export from "./routes/admin/export.ts";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_reset_data from "./routes/admin/reset-data.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AIChat from "./islands/AIChat.tsx";
import * as $Animations from "./islands/Animations.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GlobalPhotoModal from "./islands/GlobalPhotoModal.tsx";
import * as $ModalPortal from "./islands/ModalPortal.tsx";
import * as $PhotoModal from "./islands/PhotoModal.tsx";
import * as $PhotoViewer from "./islands/PhotoViewer.tsx";
import * as $ProfilePhoto from "./islands/ProfilePhoto.tsx";
import * as $SpaceBackground from "./islands/SpaceBackground.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/analytics.tsx": $admin_analytics,
    "./routes/admin/export.ts": $admin_export,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/reset-data.ts": $admin_reset_data,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AIChat.tsx": $AIChat,
    "./islands/Animations.tsx": $Animations,
    "./islands/Counter.tsx": $Counter,
    "./islands/GlobalPhotoModal.tsx": $GlobalPhotoModal,
    "./islands/ModalPortal.tsx": $ModalPortal,
    "./islands/PhotoModal.tsx": $PhotoModal,
    "./islands/PhotoViewer.tsx": $PhotoViewer,
    "./islands/ProfilePhoto.tsx": $ProfilePhoto,
    "./islands/SpaceBackground.tsx": $SpaceBackground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
